Dynamic Dejure Calculation
ParadoxGameConverters/ImperatorToCk2 pull request #36
Opened 2021-07-03 14:34 UTC by DrDudelsack

Rather then having the same 769 start historical dejure setup, dejure kingdoms and empires are now calculated and created dynamically based on culture and rank. Duchies are calculated to be dejure in a kingdom tier title based off of province ownership, the title with the most provinces in a duchy will have that entire duchy be considered dejure. 

Independent kingdoms will have a dejure empire liege generated based off of their culture, as defined in dejureConversion.txt, while empire tier titles will be considered their own dejure empires, with governorship vassals being dejure kingdoms. Empire tier titles now get an additional kingdom tier title in their directly held land, named after the capital province, used primarily to creating a hole in the generated dejure map shattered. 

As an example, if Gaul from an I:R save remains divided, there will be many dejure kingdoms that are all dejure of a unitable Gallic Empire title, while if Boi conquers all of Italia and becomes an empire, the duchies in Italia will be dejure to Boi. This dejure generation prevents many cases where countries like Rome would ahistorically userp titles that shouldn't exist, such as France or Italy

2021-07-04 05:12 UTC, Idhrendur approved these changes

2021-07-04 05:12 UTC, Idhrendur requested changes
Codacy found some issues you should address: https://app.codacy.com/gh/ParadoxGameConverters/ImperatorToCk2/pullRequest?prid=7700691

2021-07-05 09:28 UTC, DrDudelsack commented
While Codacy technically did find issues, they're minor and don't effect the code's functionality in any way. For example, Codacy doesn't like the formatProvName method for being too long, but it needs to be that size in order to correctly convert CK II's province names from the format used for localization to the format used in defines, and reassigning input parameters from within a method is a perfectly valid technique in Java

2021-07-05 19:43 UTC, Idhrendur commented
The unused variables, empty blocks, etc. are minor yes, but also easy to fix, and so should be fixed. It's good practice to take the effort to have clean code. Six month's future you will be glad you took the effort now.

As well, the "Use equals() to compare strings instead of '==' or '!='" comment is quite correct (that whole issue is one of my major annoyances with Java, but that's a whole digression). I'm somewhat surprised it works correctly in the first place, which is probably a matter of lucky accidental design.

2021-08-01 23:24 UTC, Idhrendur approved these changes

2021-08-01 23:25 UTC, merged